#!/bin/bash

export obj="a/main.o b/c/c.o b/d/d.o b/main.o c/c.o c/test_cc d/lib.o e/main.o e/test.o main.o"
export dep="main.d a/main.d b/main.d b/c/c.d b/d/d.d c/c.d d/lib.d e/main.d e/test.d"
export notes="main.gcno a/main.gcno b/main.gcno b/c/c.gcno b/d/d.gcno c/c.gcno d/lib.gcno e/main.gcno e/test.gcno"
export sha1=".compile.cc.sha1 .compile.cxx.sha1 .link.cc.sha1 .link.cxx.sha1"
export targets="a/program_a a/test_dupl b/program_b d/lib.so e/program_e e/test_program program"
export all="${obj} ${dep} ${notes} ${sha1} ${targets}"

test_start ()
{
	printf '\n\e[1;34m%s\e[0m %s\n\n' TEST "${@}"
}

assert_exist ()
{
	local object=$(readlink -f ${1})

	set +o errexit
	test -e ${object}
	result=$?
	[ "${result}" -ne 0 ] &&
		FAILURE="should exist but does not: ${object}"
	set -o errexit

	return ${result}
}

assert_not_exist ()
{
	local object=$(readlink -f ${1})

	set +o errexit
	test ! -e ${object}
	result=$?
	[ "${result}" -ne 0 ] &&
		FAILURE="should not exist but does: ${object}"
	set -o errexit

	return ${result}
}

assert_newer_than ()
{
	return 0
}

assert_older_than ()
{
	return 0
}
