#!/bin/bash

[ -z "${TEST_SETUP_INCLUDE_GUARD}" ] ||
	return 0

export TEST_SETUP_INCLUDE_GUARD=1

_TMPFILE=$(mktemp)
_TMPDIR=$(mktemp -d)

error ()
{
	[ -n "$@" ] &&
		echo "$@" >$2

	exit 1
}

interrupted ()
{
	PASSED=false
	FAILURE="tests were interrupted while executing \"${BASH_COMMAND}\""
	exit 1
}

teardown ()
{
	if [ -d "${_TMPDIR}" ]; then
		rm -rf ${_TMPDIR}
	fi
	if [ -e "${_TMPFILE}" ]; then
		rm -f ${_TMPFILE}
	fi

	make distclean >/dev/null 2>&1

	trap ERR INT EXIT
	set +o errexit

	if [ "${PASSED}" == 'true' ]; then
		printf '\nAll tests \e[1;32mPASSED\e[0m\n\n'
	else
		printf '\n\e[1;31m%s\e[0m %s\n\n' FAILED "${FAILURE:=while executing \"${BASH_COMMAND}\"}"
	fi
}

trap "PASSED=false" ERR
trap interrupted INT
trap teardown EXIT

export MYCC=$(readlink -f mycc)
export MYCXX=$(readlink -f mycxx)
cd ${CURDIR}/project
PASSED=true

set -o errexit
