#!/bin/bash

TEST=$(readlink -f ${BASH_SOURCE[0]})
CURDIR=${CURDIR:-$(dirname ${TEST})}

source ${CURDIR}/setup
source ${CURDIR}/common

test_start ${TEST}

test_step "make static"
make static
for file in ${targets} ${obj} ${dep} ${sha1}; do
	assert_exist ${file}
done
for file in ${notes}; do
	assert_not_exist ${file}
done
