#!/bin/bash

TEST=$(readlink -f ${BASH_SOURCE[0]})
CURDIR=${CURDIR:-$(dirname ${TEST})}

source ${CURDIR}/setup
source ${CURDIR}/common

test_start ${TEST}

test_step 'make static'
make static
assert_full_static_build

# FIXME Is it enough to make sure we do not have a .dynamic section in ELF?
test_step 'Verify that built binaries are statically linked'
result=0
(objdump -h program | grep -q .dynamic) || result=$?

assert_equal ${result} 1 "program should be statically linked but contains a dynamic section in the ELF header" 
