#!/bin/bash

TEST=$(readlink -f ${BASH_SOURCE[0]})
CURDIR=${CURDIR:-$(dirname ${TEST})}

source ${CURDIR}/setup
source ${CURDIR}/common

test_start ${TEST}

test_step 'make distclean'
make distclean
assert_clean
