#!/bin/bash

TEST=$(readlink -f ${BASH_SOURCE[0]})
CURDIR=${CURDIR:-$(dirname ${TEST})}

source ${CURDIR}/setup
source ${CURDIR}/common

test_start ${TEST}

test_step 'make'
make
assert_full_build

test_step 'Trigger rebuild'
touch a/main.c
make
assert_newer_than a/main.d a/main.c
