#!/bin/bash -x

TEST=$(readlink -f ${BASH_SOURCE[0]})
CURDIR=${CURDIR:-$(dirname ${TEST})}

source ${CURDIR}/setup
source ${CURDIR}/common

test_start ${TEST}

test_step 'make check'
guard=/tmp/test.sh.has.run
rm -f ${guard}
make check
assert_full_build

test_step 'Verify that test program has been run'
assert_exist ${guard}
