#!/bin/bash

TEST=$(readlink -f ${BASH_SOURCE[0]})
CURDIR=${CURDIR:-$(dirname ${TEST})}

source ${CURDIR}/setup
source ${CURDIR}/common

test_start ${TEST}

test_step make
make
touch timestamp # FIXME this can be left behind
make CFLAGS=-pipe
assert_newer_than program timestamp
rm -f timestamp
