#!/bin/bash

CURDIR=${CURDIR:-$(dirname $(readlink -f $0))}

source ${CURDIR}/setup
source ${CURDIR}/common

tmpdir=$(mktemp -d)
test_start "make BUILD_DIR=${tmpdir}"
make BUILD_DIR=${tmpdir}
for file in ${targets} ${obj} ${dep} ${sha1}; do
	assert_exist ${tmpdir}/${file}
done
for file in ${notes}; do
	assert_not_exist ${tmpdir}/${file}
done

test_start "make BUILD_DIR=${tmpdir} clean"
make BUILD_DIR=${tmpdir} clean
for file in ${all}; do
	assert_not_exist ${tmpdir}/${file}
done
