#!/bin/bash

TEST=$(readlink -f ${BASH_SOURCE[0]})
CURDIR=${CURDIR:-$(dirname ${TEST})}

source ${CURDIR}/setup
source ${CURDIR}/common

test_start ${TEST}

test_step 'make check'
guard=/tmp/test.sh.has.run
rm -f ${guard}
make check

test_step 'Verify that all required binaries have been built'
assert_exist c/test_cc
assert_exist e/program_e

test_step 'Verify that test has been run'
assert_exist ${guard}
