#!/bin/bash

TEST=$(readlink -f ${BASH_SOURCE[0]})
CURDIR=${CURDIR:-$(dirname ${TEST})}

source ${CURDIR}/setup
source ${CURDIR}/common

tmpdir=$(get_tmpdir)

test_start ${TEST}

test_step "make DESTDIR=${tmpdir} install"
make DESTDIR=${tmpdir} install
assert_full_build_no_tests

test_step 'Verify installation'
for program in ${programs}; do
	assert_exist ${tmpdir}/bin/$(basename ${program})
done
for library in ${libraries}; do
	assert_exist ${tmpdir}/lib/$(basename ${library})
done
for data in ${data} ${libdata}; do
	assert_exist ${tmpdir}/share/$(basename ${data})
done
echo ${programs} | tr ' ' '\n' | sort > ${tmpdir}/expected.programs
ls -1 ${tmpdir}/bin/ | sort > ${tmpdir}/installed.programs
built_programs=$(echo ${programs} | wc -w)
installed_programs=$(ls -1 ${tmpdir}/bin/ | wc -l)
diff -u ${tmpdir}/expected.programs ${tmpdir}/installed.programs > ${tmpdir}/diff.programs || true
diff=$(sed -n '/^[+-][a-zA-Z]/p' < ${tmpdir}/diff.programs)

assert_equal ${built_programs} ${installed_programs} "Difference compared to expected result: ${diff}"

test_step "make DESTDIR=${tmpdir} uninstall"
make DESTDIR=${tmpdir} uninstall

test_step 'Verify that project was uninstalled'
for program in ${programs}; do
	assert_not_exist ${tmpdir}/bin/$(basename ${program})
done
for library in ${libraries}; do
	assert_not_exist ${tmpdir}/lib/$(basename ${library})
done
for data in ${data} ${libdata}; do
	assert_not_exist ${tmpdir}/share/$(basename ${data})
done
