#!/bin/bash

TEST=$(readlink -f ${BASH_SOURCE[0]})
CURDIR=${CURDIR:-$(dirname ${TEST})}

source ${CURDIR}/setup
source ${CURDIR}/common

test_start ${TEST}

test_step 'make pdf'
make pdf
assert_exist d/lib.pdf

test_step 'make clean'
make clean
assert_not_exist d/lib.pdf
