#!/bin/bash

TEST=$(readlink -f ${BASH_SOURCE[0]})
CURDIR=${CURDIR:-$(dirname ${TEST})}

source ${CURDIR}/setup
source ${CURDIR}/common

test_start ${TEST}

test_step 'make info'
make info
assert_exist d/shared.info

test_step 'make clean'
make clean
assert_not_exist d/shared.info
