#!/bin/bash

TEST=$(readlink -f ${BASH_SOURCE[0]})
CURDIR=${CURDIR:-$(dirname ${TEST})}

source ${CURDIR}/setup
source ${CURDIR}/common

test_start ${TEST}

tmpdir=$(get_tmpdir)
test_step "make BUILDDIR=${tmpdir}"
make BUILDDIR=${tmpdir}

test_step 'Verify build output'
for file in ${all}; do
	assert_exist ${tmpdir}/${file}
done
for file in ${notes}; do
	assert_not_exist ${tmpdir}/${file}
done

test_step "make BUILDDIR=${tmpdir} clean"
make BUILDDIR=${tmpdir} clean

test_step 'Verify that all files were deleted'
for file in ${clean}; do
	assert_not_exist ${tmpdir}/${file}
done
