#!/bin/bash

TEST=$(readlink -f ${BASH_SOURCE[0]})
CURDIR=${CURDIR:-$(dirname ${TEST})}

source ${CURDIR}/setup
source ${CURDIR}/common

tmpdir=$(get_tmpdir)

test_start ${TEST}

test_step "make DESTDIR=${tmpdir} install-dvi"
make DESTDIR=${tmpdir} install-dvi

test_step 'Verify installation'
assert_exist ${tmpdir}/doc/lib.dvi

test_step "make DESTDIR=${tmpdir} uninstall"
make DESTDIR=${tmpdir} uninstall

test_step 'Verify uninstallation of manual pages'
assert_not_exist ${tmpdir}/doc/lib.dvi
