#!/bin/bash

CURDIR=${CURDIR:-$(dirname $(readlink -f $0))}

source ${CURDIR}/setup
source ${CURDIR}/common

test_start "make static"
make static
for file in ${targets} ${obj} ${dep} ${sha1}; do
	assert_exist ${file}
done
for file in ${notes}; do
	assert_not_exist ${file}
done
